### ISSUE TITLE
关于getAmountConfig错误

### ISSUE THREAD

**Issue by fantasy-mark** [philsong/bitcoin-broker#3]
我调试的过程有这个错误，是config.json没有设置好吗？谢谢
![image](https://cloud.githubusercontent.com/assets/1555808/21757138/35a61c5c-d665-11e6-9205-510965b13f4b.png)

**Comment by philsong** [comment]
没有配置交易所的key

**Comment by fantasy-mark** [comment]
recv msg, thx!

2017-01-14 

hacker.do 



发件人：philsong <notifications@github.com>
发送时间：2017-01-14 17:29
主题：Re: [philsong/bitcoin-broker] 关于getAmountConfig错误 (#3)
收件人："philsong/bitcoin-broker"<bitcoin-broker@noreply.github.com>
抄送："fantasy_mark"<hacker.do@163.com>,"Author"<author@noreply.github.com>

没有配置交易所的key

**Comment by boyzun** [comment]
你好，我调试过程中出现与fantasy-mark同样的错误。请问除了bitcoin-arbitrage模块需要配置key外，在bitcoin-broker模块中还需要配置吗？我在bitcoin-arbitrage中出现如下错误，但key应该是已经配置好的，查询两个账号的能正确返回数据。

[root@x3550m2-1 bitcoin-arbitrage-github]# python3 arbitrage/arbitrage.py -m OkCoinCNY,HuobiCNY get-balance
PrivateOkCoinCNY: {'btc_balance': 0.0, 'btc_frozen': 0.0, 'cny_balance': 100.53, 'cny_frozen': 0.0}
PrivateHuobiCNY: {'btc_balance': 0.0009, 'btc_frozen': 0.0, 'cny_balance': 93.27, 'cny_frozen': 0.0}
-------------------------------------------------------------------------------------------------------------------
[root@x3550m2-1 bitcoin-arbitrage-github]# python3 arbitrage/arbitrage.py -oTraderBotSim -mOKCoinCNY,HuobiCNY
2017-04-25 00:06:17,108 [INFO] BasicBot Setup complete
2017-04-25 00:06:17,359 [WARNING] load client id failed!
Traceback (most recent call last):
  File "arbitrage/arbitrage.py", line 204, in <module>
    main()
  File "arbitrage/arbitrage.py", line 201, in main
    cli.main()
  File "arbitrage/arbitrage.py", line 197, in main
    self.exec_command(args)
  File "arbitrage/arbitrage.py", line 33, in exec_command
    self.arbitrer.loop()
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/arbitrer.py", line 242, in loop
    self.tick()
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/arbitrer.py", line 204, in tick
    observer.begin_opportunity_finder(self.depths)
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/observers/traderbot.py", line 47, in begin_opportunity_finder
    self.check_order(depths)
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/observers/traderbot.py", line 70, in check_order
    if self.is_buying():
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/observers/basicbot.py", line 145, in is_buying
    return len(self.get_orders('buy')) > 0
  File "/root/BTC/bitcoin-arbitrage-github/arbitrage/observers/basicbot.py", line 132, in get_orders
    orders = [x for x in self.orders if x['type'] == type]
AttributeError: 'TraderBotSim' object has no attribute 'orders'

**Comment by qct** [comment]
交易所的  public key， secret key   要自己往数据库里面写吗？
